[files]
extend-exclude = [
    "src/external", 
    "tests/include", 
    "tests/frontend/test_*.c",
    "src/gen",
    "src/include/keywords.h"
]


[default.extend-words]
OT = "OT"
PN = "PN"
IST = "IST"
pankti = "pankti"
palash = "palash"
bauri = "bauri"
